#!/bin/bash 

### Check if any argument is provided 
if [ $# -eq 0 ]; then 
    echo "Usage: bash <https://web.prod.am-usge1.moveworks.io/r?v2_EzxiSW8U2WZpEM7I|open.sh> <filename>" 
    exit 1 
fi 

FILENAME=$1 
MATCHES=($(find . -name "$FILENAME")) 

### Determine the number of matches found 
MATCH_COUNT=${#MATCHES[@]} 

if [ $MATCH_COUNT -eq 0 ]; then 
    echo "File '$FILENAME' not found." 
    exit 1 
elif [ $MATCH_COUNT -eq 1 ]; then 
    # Create .vimrc in home directory if it doesn't exist
    if [ ! -f ~/.vimrc ]; then
        cat > ~/.vimrc <<'EOF'
        " Display existing tab characters as 4 spaces
        set tabstop=4
        " Use 4 spaces for each step of (auto)indent
        set shiftwidth=4
        " When the <Tab> key is pressed, insert spaces instead of a tab character
        set expandtab
        " Ensure syntax highlighting remains enabled
        syntax on
        
EOF
    fi
    vim "${MATCHES}" 
else 
    echo "Multiple files found:" 
    printf '%s\n' "${MATCHES[@]}" 
    exit 1 
fi
